name: Deploy Terraform Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Verify Terraform installation
      - name: Verify Terraform
        run: terraform version

      # Go into terraform directory
      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ./templates/terraform

      # Validate Terraform code
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./templates/terraform

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./templates/terraform

      # Deploy Infrastructure
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./templates/terraform